### ISSUE TITLE
Store page missing screenshots

### ISSUE THREAD

**Issue by popey** [timsueberkrueb/cavestory-snap#1]
I'd like to promote the cavestory snap in the snap store editor's picks and on social media. However we prefer to promote applications which have pretty store pages. This can include screenshots or an embedded video to entice new users.

It might also be useful to list the default controls, or some back story on the store page.

We have a blog post which details some recommended tips for improving the page. 
https://snapcraft.io/blog/make-your-snap-store-page-pop

Once done, close this issue, and I'll schedule the social posts :)

**Comment by timsueberkrueb** [comment]
Done :)

**Comment by popey** [comment]
Thanks @timsueberkrueb
